<?php
$arr = [
    "Logo",
    "Home",
    "Service",
    "Sign Out",
    "My Profile",
    "Login",
    "Register",
    "Logout",
    "Remember me",
    "Forgot Password",
    "Create account",
    "Don\'t have an account?",
    "Password",
    "Email Or Username",
    "Sponsor Name",
    "Sponsor By",
    "First Name",
    "Last Name",
    "Username",
    "Email Address",
    "Your Phone Number",
    "Password",
    "Confirm Password",
    "Enter Captcha",
    "I Agree with the Terms & conditions",
    "sign up",
    "Login here",
    "Already have an account?",
    "You don’t have permission to access ‘/’ on this server.",
    "Back To Home",
    "Method not allowed",
    "Session has expired",
    "The server encountered an internal error misconfiguration and was unable to complate your request. Please contact the server administrator.",
    "Login",
    "Dashboard",
    "about image",
    "API DETAILS",
    "API URL",
    "API KEY",
    "API KEY",
    "HTTP METHOD",
    "RESPONSE FORMAT",
    "PLACE NEW ORDER",
    "key",
    "action",
    "service",
    "link",
    "quantity",
    "Your API key",
    "add",
    "Service ID",
    "Link to page",
    "Link to page",
    "Needed quantity",
    "runs",
    "Runs to deliver",
    "optional",
    "interval",
    "Interval in minutes",
    "STATUS ORDER",
    "Order ID",
    "MULTIPLE STATUS ORDER",
    "Order IDs separated by comma (array data)",
    "orders",
    "PLACE REFILL",
    "refill",
    "order",
    "SERVICE LIST",
    "services",
    "USER BALANCE",
    "balance",
    "thumbnail image",
    "Read More",
    "No blogs available to display.",
    "Image Description",
    "Admin",
    "call-to-action image",
    "Address",
    "phone image",
    "Email",
    "email image",
    "Phone",
    "Full Name",
    "Subject",
    "Your message",
    "Send Message",
    "counter image",
    "Feature Image",
    "Support",
    "Quick Links",
    "Enter email",
    "All rights reserved",
    "Hero Img",
    "Payment Partner",
    "service image",
    "client image",
    "Thumbnail Image",
    "Recent Posts",
    "Google",
    "Facebook",
    "Github",
    "Username or Email",
    "User Name",
    "Resend code",
    "Didn't get Code? Click to",
    "Submit",
    "Your email address is",
    "Verify Your Email",
    "Verify Your Phone Number",
    "Your phone number is",
    "Two Step Security",
    "Code",
    "Profile Image",
    "View Profile",
    "Support Ticket",
    "My Profile",
    "Sign Out",
    "About Image One",
    "About Image Two",
    "API Documentation",
    "Note: Please read the API instructions carefully. Its your solo responsibility what you add by our API.",
    "Parameter",
    "Description",
    "POST",
    "Response format",
    "Json",
    "PLACE NEW ORDER",
    "Runs to deliver",
    "Link to page",
    "Example response",
    "Generate Api Key",
    "Would you like to generate a new API key?",
    "Close",
    "Supported Currency",
    "Deposit Summery",
    "cancel this transfer",
    "confirm and continue",
    "Deposit History",
    ""





];
return $arr;

